services:
  backend:
    build: ./backend
    container_name: pdf_backend
    ports:
      - "8001:8000"
    volumes:
      - uploaded_pdfs:/app/uploaded_pdfs # Persist uploaded files
      - logs:/app/logs # Persist log files
      - database:/app/tasks.db # Persist the SQLite database file
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: pdf_frontend
    ports:
      - "3500:80" # Map host port 3000 to container port 80 (Nginx)
    environment:
      # This tells the frontend how to reach the backend service
      - VITE_API_URL=http://backend:8000
    depends_on:
      - backend # Ensures the backend is started before the frontend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  uploaded_pdfs:
  logs:
  database:
