services:
  backend:
    build: ./backend
    container_name: pdf_backend
    ports:
      - "8001:8000"
    volumes:
      # Mount directories instead of files for reliability
      - uploaded_pdfs:/app/uploaded_pdfs
      - logs:/app/logs
      - database_data:/app/database  # <-- CHANGED THIS LINE
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend # We just need the context now
    container_name: pdf_frontend
    ports:
      - "3500:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  uploaded_pdfs:
  logs:
  database_data:
